name: Export ECAD
on:
  push:

jobs:
  export-ecad:
    name: Export ECAD
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad7_auto:1.6.2
    steps:

    - name: Update system repositories, Install Required Libraries and Initialize git-lfs
      run: |
        apt update
        apt -y install git git-lfs zip librsvg2-bin imagemagick
        git lfs install

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        lfs: true


    - name: Update the PCBs with git hash
      run: |
        export COMMIT=$(git rev-parse --short HEAD)
        echo "COMMIT = ${COMMIT}"    
        echo "ref: ${{ github.ref }}"
        echo "default: ${{ env.default }}"
        sed -i "s!<<hash>>!${COMMIT}!" r2_warpcore_driver.kicad_pcb

    - name: Generate Export Files
      uses: INTI-CMNB/KiBot@v2_k7
      with:
          config: .github/workflows/scripts/kibot/config.kibot.yaml
          schema: r2_warpcore_driver.kicad_sch
          board: r2_warpcore_driver.kicad_pcb
          dir: r2_warpcore_driver

    - name: Upload Export Files as Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: r2_warpcore_driver
        path: r2_warpcore_driver
        if-no-files-found: error
        retention-days: 60
    
